# Generated by Django 5.1.7 on 2025-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_alter_income_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='regency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='village',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
