# Generated by Django 5.1.7 on 2025-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_alter_province_code_alter_regency_code_and_more'),
        ('pmb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='id',
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.income'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.job'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='kk',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nik',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Calon_mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.citizen')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.faculty')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.gender')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmb.parent')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.province')),
                ('regency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.regency')),
                ('registrationpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.registrationpath')),
                ('registrationperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.registrationperiod')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.religion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.school')),
                ('studyprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.studyprogram')),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subdistrict')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.village')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
