# Generated by Django 5.1.7 on 2025-05-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmb', '0002_remove_parent_id_alter_parent_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiBayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bukti_bayar/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('calon_mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_bayar', to='pmb.calon_mahasiswa')),
            ],
            options={
                'ordering': ['tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='BuktiIdentitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bukti_identitas/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('calon_mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_identitas', to='pmb.calon_mahasiswa')),
            ],
            options={
                'ordering': ['tanggal_upload'],
            },
        ),
    ]
