# Generated by Django 5.1.7 on 2025-05-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmb', '0003_buktibayar_buktiidentitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktibayar',
            name='calon_mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_bayar', to='pmb.calon_mahasiswa'),
        ),
        migrations.AlterField(
            model_name='buktiidentitas',
            name='calon_mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_identitas', to='pmb.calon_mahasiswa'),
        ),
    ]
