# Generated by Django 5.1.7 on 2025-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmb', '0004_alter_buktibayar_calon_mahasiswa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
