# Generated by Django 5.1.7 on 2025-06-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmb', '0005_registration_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_number', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('Calon_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pmb.calon_mahasiswa')),
            ],
        ),
    ]
