# Generated by Django 5.1.7 on 2025-06-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmb', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Calon_mahasiswa',
            new_name='calon_mahasiswa',
        ),
    ]
